Updated Browsing and Downloading Page
mybb/docs.mybb.com pull request #145
Opened 2017-02-11 20:11 UTC by chack1172

Updated Browsing and Downloading page to the new layout of extend website.

2017-02-12 22:37 UTC, Ben-MyBB commented
Looks good to me. Thanks for the contribution.

2017-02-12 22:37 UTC, Ben-MyBB approved these changes

2017-02-12 22:42 UTC, Shade- commented
There are some language mistakes here and there though. Would be nice if a native speaker addressed them.

2017-02-12 22:45 UTC, Ben-MyBB commented
@Shade- Looks fine to me? @andrewjs18

2017-02-12 22:50 UTC, Shade- requested changes

2017-02-12 22:50 UTC, Shade- commented on extend/browsing-downloading-from-extend.md
> +For each projects you can view the cover and this informations:
For each **project** you can view the cover and **these** informations

2017-02-12 22:50 UTC, Shade- commented on extend/browsing-downloading-from-extend.md
> +On the right side, you can see the latest build and a Donate button if the owner of the project set a PayPal e-mail for donations.
... if the owner of the project **sets**

2017-02-12 22:52 UTC, Shade- commented
These are a couple of them. There may be others.

2017-02-12 22:53 UTC, Ben-MyBB commented on extend/browsing-downloading-from-extend.md
> +For each projects you can view the cover and this informations:
This doesn't make sense. I'd put- for each project you can view the cover and the following information:

2017-02-12 22:53 UTC, Ben-MyBB commented on extend/browsing-downloading-from-extend.md
> +On the right side, you can see the latest build and a Donate button if the owner of the project set a PayPal e-mail for donations.
Good spot.

2017-02-12 22:55 UTC, chack1172 commented on extend/browsing-downloading-from-extend.md
> +For each projects you can view the cover and this informations:
You're right.

2017-02-12 22:56 UTC, chack1172 commented on extend/browsing-downloading-from-extend.md
> +On the right side, you can see the latest build and a Donate button if the owner of the project set a PayPal e-mail for donations.
I think that set is correct (it's not present)

2017-02-12 22:58 UTC, Ben-MyBB commented on extend/browsing-downloading-from-extend.md
> +On the right side, you can see the latest build and a Donate button if the owner of the project set a PayPal e-mail for donations.
I would say this sounds better:

On the right side, you can see the latest build and a Donate button if the owner of the project has set a PayPal e-mail for donations.

2017-02-12 22:59 UTC, Shade- commented on extend/browsing-downloading-from-extend.md
> +On the right side, you can see the latest build and a Donate button if the owner of the project set a PayPal e-mail for donations.
Either you use present tense (sets) or present perfect (has set). I'd go with the latter.

2017-02-12 23:08 UTC, Shade- approved these changes

2017-10-14 17:02 UTC, Ben-MyBB commented
@Shade- This looks fine to me. Any further changes you'd like?

2017-10-14 20:18 UTC, Shade- commented
There are still some issues. I will review this later when I come home.

2017-10-15 11:23 UTC, Shade- requested changes

2017-10-15 11:23 UTC, Shade- commented on extend/browsing-downloading-from-extend.md
> +Clicking the project names or the Details button directs you towards the project page, on which you can see detailed information: full description, previews, license, suggestions, bugs, etc.
Clicking the project **name**

2017-10-15 11:23 UTC, Shade- commented on extend/browsing-downloading-from-extend.md
> +Under this buttons there is a tab with the following links:
Under **these** buttons

2017-10-15 11:23 UTC, chack1172 commented on extend/browsing-downloading-from-extend.md
> +Clicking the project names or the Details button directs you towards the project page, on which you can see detailed information: full description, previews, license, suggestions, bugs, etc.
Nice spot :)

2017-10-15 11:24 UTC, chack1172 commented on extend/browsing-downloading-from-extend.md
> +Under this buttons there is a tab with the following links:
You're right. My english is bad...

2020-05-03 20:56 UTC, merged