Grammar/Rewording
mybb/docs.mybb.com pull request #151
Opened 2017-05-23 08:15 UTC by LewisHolt

I've just rewritten a bit of this page, I found it earlier and it definitely needed some touch ups. I don't believe I've missed anything!

2017-05-23 16:47 UTC, euantorano requested changes
Looks good, just some slight changes :smile:

2017-05-23 16:47 UTC, euantorano commented on 1.8/administration/user-titles.md
> +User titles is text that is displayed under the username in posts, threads, profile and on the member list.
`User titles are text` sounds more grammatically correct to me.

2017-05-23 16:47 UTC, euantorano commented on 1.8/administration/user-titles.md
> +
What's with these extra blank lines?

2017-10-14 16:59 UTC, Ben-MyBB commented
@LewisHolt any update on the changes?

2017-10-14 17:45 UTC, WildcardSearch requested changes
Good work, just a few nits.

2017-10-14 17:45 UTC, WildcardSearch commented on 1.8/administration/user-titles.md
> +#### Set User Titles According to the Group
This should be in **Title Case**

2017-10-14 17:45 UTC, WildcardSearch commented on 1.8/administration/user-titles.md
> +You can specify the user title name, minimum number of posts, number of stars and the amount of stars at `Admin Control Panel -> Users & Groups -> User Titles`.
Forgot the Oxford comma:

`number of stars, and the amount of stars`

2017-10-14 17:45 UTC, WildcardSearch commented on 1.8/administration/user-titles.md
> +Here you can write the minimum number of posts required before the user will be assigned a Custom User Title.
I'm thinking "write" should be "enter" or "set".

2017-12-03 10:08 UTC, closed without merging