MyBB website redesign
mybb/docs.mybb.com pull request #167
Opened 2018-01-05 12:53 UTC by justinsoltesz

**THIS IS NOT READY TO MERGE** and should not be merged until the entire new site is ready for launch.

This implements the new website design to the docs site.

2018-09-26 21:21 UTC, dvz requested changes

2018-09-26 21:21 UTC, dvz commented on .gitignore
> -Gemfile
I believe this can be restored

2018-09-26 21:21 UTC, dvz commented on _config.yml
> +baseurl: /docs.mybb.com # MUST BE REMOVED BEFORE SUBMITTING PULL REQUEST
Shouldn't that be removed?

2018-09-27 22:32 UTC, justinsoltesz commented
changes have been made, this should be ready to launch

2018-09-27 22:54 UTC, dvz approved these changes

2018-10-14 20:21 UTC, merged