Create cache-handlers.md
mybb/docs.mybb.com pull request #193
Opened 2020-05-03 20:53 UTC by Ben-MyBB

This is still a work in progress.

2020-05-10 13:26 UTC, Ben-MyBB commented
@euantorano can you have a quick read through when you get a sec? If this is the sort of thing we want to go for I can finish this off (still have things to add like how to select each one).

2020-05-10 13:28 UTC, euantorano commented
Yep, will have a look today thanks.

2020-05-10 13:37 UTC, euantorano requested changes
Looks good so far, just some minor comments.

2020-05-10 13:37 UTC, euantorano commented on 1.8/administration/cache-handlers.md
> +RFC 2616 compliant caching provides a mechanism to verify whether stale or expired content is still fresh, and can represent a significant performance boost when the origin server supports conditiona
Our cache handler is just a file based cache. I'd suggest something like:

```suggestion
Cache file are written to the filesystem within the `cache/` directory as PHP files. The `cache/` directory must be writeable for this cache handler to function.
```

2020-05-10 13:37 UTC, euantorano commented on 1.8/administration/cache-handlers.md
> +Please note, eAccelerator is no longer officially supported.
Supported by MyBB, not by upstream:
```suggestion
Please note, eAccelerator is no longer officially supported by the upstream developers.
```

2020-05-23 21:32 UTC, euantorano requested changes
Sorry, minor spelling/grammar tweak.

2020-05-23 21:32 UTC, euantorano commented on 1.8/administration/cache-handlers.md
> +Cache file are written to the filesystem within the `cache/` directory as PHP files. The `cache/` directory must be writeable for this cache handler to function.
```suggestion
Cache files are written to the filesystem within the `cache/` directory as PHP files. The `cache/` directory must be writeable for this cache handler to function.
```

2020-05-23 21:35 UTC, euantorano requested changes

2020-05-23 21:35 UTC, euantorano commented on 1.8/administration/cache-handlers.md
> +Don't forget, if you wish to use Redis or Memcache you will also need to set the Hostname and Port settings which are also set in the config.php file. The setting for Memcache can be found at line 50
```suggestion
Don't forget, if you wish to use Redis or Memcache you will also need to set the Hostname and Port settings which are also set in the config.php file. The settings for Memcache can be found at line 50 and the settings for Redis can be found at line 62. You will edit the Hostname and Port number values similiar to above.
```

2020-05-23 21:35 UTC, euantorano commented
This looks good, just a couple of minor tweaks.

2020-05-23 22:32 UTC, dvz commented
Are `mod_cache`, https://redis.io/topics/client-side-caching relevant here?

2020-05-23 22:48 UTC, euantorano commented
I don't think so - this is specifically for the built in cache interface for back-end caching.

2020-05-30 15:24 UTC, Ben-MyBB commented
Thanks @euantorano. Applied both of your suggestions.

2020-05-30 15:25 UTC, euantorano commented
Awesome, thanks. I’ll have another look over, hen this should be good to merge I believe?

2020-05-30 15:28 UTC, Ben-MyBB commented
Yep, I don't think I have anything else to add.

2020-05-30 15:29 UTC, euantorano requested changes

2020-05-30 15:29 UTC, euantorano commented on 1.8/administration/cache-handlers.md
> +https://httpd.apache.org/docs/2.4/mod/mod_cache.html
Probably best to remove this link, as `mod_cache` is something different. 

```suggestion
```

2020-05-30 15:29 UTC, euantorano commented on 1.8/administration/cache-handlers.md
> +
Might be best to add a horizontal rule here.

```suggestion
—————
```

2020-05-30 15:32 UTC, Ben-MyBB commented
@euantorano updated :)

2020-05-30 15:32 UTC, closed without merging