recommend latest mariadb
mybb/docs.mybb.com pull request #206
Opened 2024-06-03 12:03 UTC by robertsilen

2024-06-03 17:06 UTC, Sama34 requested changes

2024-06-03 17:06 UTC, Sama34 commented on 1.8/install/requirements.md
> +- latest version of PostgreSQL or MariaDB
```suggestion
- latest version of PostgreSQL, MySQL, or MariaDB
```

2024-06-03 17:07 UTC, Sama34 commented on 1.8/install/requirements.md
> +- latest version of PostgreSQL or MariaDB
You could toggle the order if you so prefer, just keep them both please.

2024-06-12 13:30 UTC, robertsilen commented
@Sama34 Is it ok now? :)

2024-07-04 12:57 UTC, merged